#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
echo ${HERE}
export PREFIX=$HERE/usr
export PATH=$PREFIX/bin:$PATH
export LD_LIBRARY_PATH=$PREFIX/lib${LD_LIBRARY_PATH:+':'}$LD_LIBRARY_PATH
export PYTHONHOME=$PREFIX
# export PYTHONPATH=`echo $PREFIX/lib/python3*`
export PATH_TO_FREECAD_LIBDIR=$PREFIX/lib
# export GSETTINGS_SCHEMA_DIR=$PREFIX/share/glib-2.0/schemas:$GSETTINGS_SCHEMA_DIR
# export QT_PLUGIN_PATH=$PREFIX/plugins
# export QT_XKB_CONFIG_ROOT=$PREFIX/lib
export FONTCONFIG_FILE=/etc/fonts/fonts.conf
export FONTCONFIG_PATH=/etc/fonts
export PYTHONDONTWRITEBYTECODE=1

# SSL
# https://forum.freecadweb.org/viewtopic.php?f=4&t=34873&start=20#p327416
export SSL_CERT_FILE=$PREFIX/ssl/cacert.pem
# https://github.com/FreeCAD/FreeCAD-AppImage/pull/20
export GIT_SSL_CAINFO=$PREFIX/ssl/cacert.pem
export GIT_EXEC_PATH=$PREFIX/libexec/git-core
# https://github.com/FreeCAD/FreeCAD-Bundle/issues/92#issuecomment-1086829486
export QTWEBENGINE_DISABLE_SANDBOX=1

#export GDK_PIXBUF_MODULE_FILE=$PREFIX/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
#export QT_QPA_PLATFORMTHEME=gtk2
#export GTK_PATH=$PREFIX/lib/gtk-2.0
#export GTK_DATA_PREFIX=$PREFIX
#export XDG_DATA_DIRS=$PREFIX/share/:$XDG_DATA_DIRS

name=FreeCAD
if [ "${ARGV0#*NoHDPI*}" = "$ARGV0" ]; then
    export QT_AUTO_SCREEN_SCALE_FACTOR=1
fi
if [ ! -z "$1" ] && [ -e "$PREFIX/bin/$1" ] ; then
    name=$1
    shift
else
    if [ "${ARGV0#*cmd*}" = 'cmd' ]; then
        name=${name}Cmd
    elif [ "$1" = 'cmd' ]; then
        shift
        name=${name}Cmd
    fi
    if test -e "$PREFIX/bin/$name"Link; then
        name=${name}Link
    fi
fi

cd $PREFIX/bin
"./$name" "$@"
