{% set name = "coin3d" %}
{% set version = "4.0.0" %}
{% set build = "20210915" %}
{% set sha256 = "461e567a909faa15181b9405d7541d51345b60549e0dc96d000fd79147fe29b3" %}
{% set version_superglue = "1.3.0" %}
{% set sha256_superglue = "f408adcfb706e7c781db9c218ef9e8ba56d43995ccb61dffad5f6154c34f17d6" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    - url: https://github.com/realthunder/coin/archive/Coin-{{ build }}.tar.gz
      sha256: {{ sha256 }}

    - url: https://github.com/coin3d/superglu/archive/superglu-{{ version_superglue }}.tar.gz
      sha256: {{ sha256_superglue }}
      folder: superglue
      patches:
        - superglue.patch

build:
    number: {{ build }}
    # skip: true
    # skip: true  # [win and py<35]

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libXxf86vm') }}  # [linux]
        - cmake 3.18.*
        - ninja
    host:
        - boost-cpp 1.74
        - libglu  # [linux]
        - xorg-libxt  # [linux]
        - xorg-libxi  # [linux]
        - expat
    run:
        - libglu  # [linux]
        - xorg-libxt  # [linux]
        - xorg-libxi  # [linux]
        - expat

test:
    requires:
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    files:
        - test.cpp  # [linux]
    commands:
        - ${CXX} -o test test.cpp -Wl,-rpath-link -lCoin -L${PREFIX}/lib/ -I${PREFIX}/include/  # [linux]
        - ./test  # [linux]
        - where /r "%PREFIX%"  Coin4.dll  # [win]
        - test -f ${PREFIX}/lib/libCoin.dylib  # [osx]

about:
    home: https://bitbucket.org/Coin3D/coin/wiki/Home
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: Coin3D is a c++ high-level 3D graphics toolkit.
    description: Coin3D is a high-level, retained-mode toolkit 
                 for effective 3D graphics development.
                 It is API compatible with Open Inventor 2.1.
    doc_url: https://bitbucket.org/Coin3D/coin/wiki/Home
    dev_url: https://bitbucket.org/Coin3D/coin/wiki/Home

extra:
    recipe-maintainers:
        - looooo
