{% set name = "fcitx-qt5" %}
{% set version = "1.2.5" %}
{% set sha256 = "b45183d9a51a65dacaed33726587a1604d09c77adffea9f02735085e9335053d" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}_{{ version }}_fc.tar.gz
    url: https://github.com/fcitx/{{ name }}/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 2
    skip: true  # [not linux]
    # skip: true

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ cdt('xorg-x11-proto-devel') }} # [linux]
        - cmake
        - ninja
    host:
        - qt 5.15.4
        - extra-cmake-modules
    run:
        - qt 5.15.4

