build_deps="build-essential\
            doxygen\
            apt-utils\
            wget\
            devscripts\
            desktop-file-utils\
            fakeroot\
            git\
            cmake\
            debhelper\
            dh-exec\
            dh-python\
            libboost-date-time-dev\
            libboost-dev\
            libboost-filesystem-dev\
            libboost-graph-dev\
            libboost-iostreams-dev\
            libboost-program-options-dev\
            libboost-python-dev\
            libboost-regex-dev\
            libboost-serialization-dev\
            libboost-signals-dev\
            libboost-thread-dev\
            libcoin-dev\
            libopencv-dev\
            libeigen3-dev\
            libgts-bin\
            libgts-dev\
            libkdtree++-dev\
            libmedc-dev\
            libocct-data-exchange-dev\
            libocct-ocaf-dev\
            libocct-visualization-dev\
            libproj-dev\
            libpyside2-dev\
            libqt5opengl5-dev\
            libqt5svg5-dev\
            libqt5webkit5-dev\
            libqt5x11extras5-dev\
            libshiboken2-dev\
            libspnav-dev\
            libvtk7-dev\
            libx11-dev\
            libxerces-c-dev\
            libzipios++-dev\
            lsb-release\
            occt-draw\
            pyside2-tools\
            python-pyside2.qtcore\
            python-pyside2.qtgui\
            python-pyside2.qtsvg\
            python-pyside2.qtuitools\
            python-pyside2.qtwidgets\
            python-pyside2.qtxml\
            python-dev\
            python-ply\
            python3-pyside2.qtcore\
            python3-pyside2.qtgui\
            python3-pyside2.qtsvg\
            python3-pyside2.qtuitools\
            python3-pyside2.qtwidgets\
            python3-pyside2.qtxml\
            python3-dev\
            python3-ply\
            qtbase5-dev\
            qttools5-dev\
            swig"
