build_deps="build-essential\
            doxygen\
            apt-utils\
            wget\
            devscripts\
            desktop-file-utils\
            fakeroot\
            git\
            cmake\
            debhelper\
            dh-exec\
            dh-python\
            libboost-date-time-dev\
            libboost-dev\
            libboost-filesystem-dev\
            libboost-graph-dev\
            libboost-iostreams-dev\
            libboost-program-options-dev\
            libboost-python-dev\
            libboost-regex-dev\
            libboost-serialization-dev\
            libboost-signals-dev\
            libboost-thread-dev\
            libcoin80-dev\
            libopencv-dev\
            libeigen3-dev\
            libgts-bin\
            libgts-dev\
            libkdtree++-dev\
            libmedc-dev\
            libocct-data-exchange-dev\
            libocct-ocaf-dev\
            libocct-visualization-dev\
            libproj-dev\
            libpyside-dev\
            libqt4-dev\
            libqt4-opengl-dev\
            libqtwebkit-dev\
            libshiboken-dev\
            libspnav-dev\
            libvtk6-dev\
            libx11-dev\
            libxerces-c-dev\
            libzipios++-dev\
            lsb-release\
            occt-draw\
            pyside-tools\
            python-pyside.qtcore\
            python-pyside.qtgui\
            python-pyside.qtsvg\
            python-pyside.qtuitools\
            python-pyside.qtxml\
            python-dev\
            python-ply\
            swig"
