{% set name = "freecad-rt" %}

package:
  name: {{ name }}
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
  path : ../../repo

build:
  number: 4

requirements:
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("11.0") }}   # [osx and arm64]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx and x86_64]
  build:
    - {{ compiler("cxx") }}
    # - {{ stdlib("c") }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - cmake
    - ninja
    - git
    - sed  # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - qt-main                                # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - libboost-devel
    - python
    - qt-main
    - qt-webengine
    - occt 7.7.2
    - xerces-c
    - zlib
    - vtk 9.2.6
    - eigen
    - pybind11
    - coin3d-rt
    - pivy-rt
    - pyside2
    - smesh
    - hdf5 
    - freetype
    - libspnav  # [linux]
    - pcl
    - six
    - ply
    - fmt ==9.1.0
    - matplotlib-base
    - xorg-xproto   # [linux]
    - yaml-cpp
    - tbb-devel  # [win]
  run:
    - python
    - occt 7.7.2
    - pyside2
    - vtk 9.2.6
    - xerces-c
    - zlib
    - hdf5
    - coin3d-rt
    - pivy-rt
    - freetype
    - numpy
    - six
    - future
    - pyyaml
    - libspnav  # [linux]
    - {{ pin_compatible('smesh', max_pin='x.x.x') }}
    - pcl
    - ply
    - gmsh
    - graphviz

# test:
#   commands:
#     # - FreeCADCmd -t 0
#     - FreeCADCmd --version

about:
  home: https://github.com/realthunder/FreeCAD
  license: LGPL2
  license_family: LGPL
  license_file: LICENSE
  summary: 'FreeCAD Link Branch'
  description: |
    FreeCAD Link Branch with various enhancement

extra:
  recipe-maintainers:
    - realthunder
