{% set name = "freecad-rt" %}

package:
  name: {{ name }}
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
  git_url : ../../repo

build:
  number: 3

requirements:
  run_constrained:
    - moab * mpi_openmpi_tempest* # [not osx]
    - moab * mpi_mpich_tempest* # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.12") }}  # [osx]
  build:
    - {{ compiler("cxx") }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - cmake
    - ninja
    - git
    - sed  # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - qt-main                                # [build_platform != target_platform]
  host:
    - boost-cpp
    - python
    - qt-main           # [not win]
    - qt-main 5.15.6    # [win]
    - qt-webengine
    - occt 
    - xerces-c
    - zlib
    - vtk
    - swig
    - eigen
    - pybind11
    - coin3d-rt
    - pivy-rt
    - pyside2
    - smesh-rt ==9.9
    - hdf5 
    - freetype
    - libspnav  # [linux]
    - pcl
    - six
    - ply
    - fmt ==9.1.0
  run:
    - python
    - qt-main           # [not win]
    - qt-main 5.15.6    # [win]
    - qt-webengine
    - occt
    - pyside2
    - vtk
    - xerces-c
    - zlib
    - boost-cpp
    - hdf5
    - coin3d-rt
    - pivy-rt
    - freetype
    - numpy
    - six
    - future
    - pyyaml
    - libspnav  # [linux]
    - {{ pin_compatible('smesh-rt', max_pin='x.x.x') }}
    - pcl
    - ply
    - gmsh
    - graphviz
    - fmt ==9.1.0
    - matplotlib

# test:
#   commands:
#     # - FreeCADCmd -t 0
#     - FreeCADCmd --version

about:
  home: https://github.com/realthunder/FreeCAD
  license: LGPL2
  license_family: LGPL
  license_file: LICENSE
  summary: 'FreeCAD Link Branch'
  description: |
    FreeCAD Link Branch with various enhancement

extra:
  recipe-maintainers:
    - realthunder
