name: Conda builder

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      arch:
        required: true
        type: string
      python-version:
        required: true
        type: string
      ref:
        required: true
        type: string
      use_mamba:
        required: false
        default: true
        type: boolean
    secrets:
      token:
        required: true
jobs:
  build:
    name: Conda build for ${{ inputs.os }} ${{ inputs.arch }} py${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    outputs:
      changelog: ${{ steps.setup.outputs.changelog }}
    steps:
      - name: Checkout build scripts
        uses: actions/checkout@v3
        with:
          repository: realthunder/FreeCADMakeImage
          submodules: true
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          repository: realthunder/FreeCAD
          ref: ${{ inputs.ref }}
          path: ./repo
          # submodules: true
      - name: Conda environment creation and activation
        uses: realthunder/setup-miniconda@main
        with:
          python-version: ${{ inputs.python-version }}
          architecture: ${{ inputs.arch == 'aarch64' && '64' || inputs.arch }}
          environment-file: conda/freecad_asm3/build_env.yaml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
          miniforge-variant: Miniforge3
          miniforge-version: latest
      - name: Install mamba build
        if: inputs.use_mamba
        shell: bash -el {0}
        run: mamba install boa -c conda-forge
      - name: Set build variant
        id: setup
        shell: bash -xel {0}
        run: |
          if ${{ startsWith(inputs.os, 'macos') }}; then
            platform=osx
          elif ${{ endsWith(inputs.os, 'mac') }}; then
            platform=osx
          elif ${{ startsWith(inputs.os, 'windows') }}; then
            platform=win
          else
            platform=linux
          fi
          if test -f repo/ChangeLog.md; then
            changelog=`sed -n "/-- ${{ inputs.ref }} --/=" repo/ChangeLog.md`
          fi
          if test -z $changelog; then
            echo "Warning: no change log"
            echo "changelog='Release ${{ inputs.ref }}'" >> "$GITHUB_OUTPUT"
          else
            EOF=EOF${{ inputs.os }}${{ inputs.arch }}${{ inputs.python-version }}${{ inputs.ref }}
            echo "changelog<<$EOF" >> "$GITHUB_OUTPUT"
            head -$((changelog - 1)) repo/ChangeLog.md >> "$GITHUB_OUTPUT"
            echo "$EOF" >> "$GITHUB_OUTPUT"
          fi
          printf "target_platform:\n  - %s-%s\n" $platform ${{ inputs.arch }} > conda/freecad_asm3/variant.yaml
          cat conda/freecad_asm3/variant.yaml
      - name: Build and upload the conda packages
        uses: realthunder/action-build-and-upload-conda-packages@main
        with:
          meta_yaml_dir: conda/freecad_asm3
          mambabuild: ${{ inputs.use_mamba }}
          python-version: ${{ inputs.python-version }}
          variant_conf: conda/freecad_asm3/variant.yaml
          user: realthunder
          label: main
          # debug: true
          token: ${{ secrets.token }}
          overwrite: true
          artifacts_name: artifacts

  bundle:
    needs: build
    uses: ./.github/workflows/bundler.yaml
    with:
      os: ${{ inputs.os }}
      arch: ${{ inputs.arch }}
      python-version: ${{ inputs.python-version }}
      ref: ${{ inputs.ref }}
      changelog: ${{ needs.build.outputs.changelog }}
