name: Make conda bundle

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  make:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2019]
        python-version: ["3.11"]
        arch : ["64"]
        include:
          - os: windows-2019
            python-version: "3.8"
            arch: "64"
          - os: ubuntu-latest
            python-version: "3.11"
            arch: "aarch64"
          - os: self-hosted-mac
            arch: arm64
            python-version: "3.11"

    uses: ./.github/workflows/builder.yaml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      python-version: ${{ matrix.python-version }}
      ref: ${{ inputs.ref }}
    secrets:
      token: ${{ secrets.token }}
