name: Make bundle

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  make_bundle:
    name: Make bundle on ${{ matrix.os }} ${{ matrix.arch }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, ubuntu-latest, windows-latest]
        python-version: ["3.10"]
        arch : ["64"]
        include:
          - os: windows-latest
            python-version: "3.8"
            arch: "64"

    steps:
      - uses: actions/checkout@v3
        with:
          repository: realthunder/FreeCADMakeImage
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
          # use-mamba: ${{ startsWith(matrix.os, 'macos') }}
          miniforge-variant: Mambaforge
      - name: Make bundle
        id: make
        shell: bash -xl {0}
        working-directory: .
        run: |
            if ${{ startsWith(matrix.os, 'windows') }}; then
                conda info
            elif ${{ startsWith(matrix.os, 'macos') }}; then
                export CONDA_CMD=mamba
            fi
            # conda is exposed as a bash function, and it seems it is not
            # accessible if calling another script on Windows (Linux seems
            # fine), so try source it.
            . conda/make-bundle.sh ${{ github.ref_name }} ${{ matrix.python-version }}

      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          fail-if-no-assets: false
          fail-if-no-release: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.make.outputs.RELEASE_NAME }}
          # repository: realthunder/FreeCAD
          assets: |
              ${{ steps.make.outputs.RELEASE_ASSETS }}

      - name: Upload release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.txt
          files: build/out/*
          name: ${{ steps.make.outputs.RELEASE_NAME }}
          prerelease: ${{ steps.make.outputs.IS_PRERELEASE }}
          tag_name: ${{ steps.make.outputs.RELEASE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
