name: Make conda bundle

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  make:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]
        arch : ["64"]
        include:
          - os: ubuntu-24.04-arm
            python-version: "3.11"
            arch: "aarch64"
          - os: macos-latest
            python-version: "3.11"
            arch: arm64

    # uses: ./.github/workflows/builder.yaml
    # with:
    #   os: ${{ matrix.os }}
    #   arch: ${{ matrix.arch }}
    #   python-version: ${{ matrix.python-version }}
    #   ref: ${{ inputs.ref }}
    #   use_mamba: false
    # secrets:
    #   token: ${{ secrets.token }}

    uses: ./.github/workflows/bundler.yaml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      python-version: ${{ matrix.python-version }}
      ref: ${{ inputs.ref }}
