name: Make bundle

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  make_bundle:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, ubuntu-latest, windows-latest]
        python-version: ["3.10"]
        arch : ["64"]
        include:
          - os: windows-latest
            python-version: "3.8"
            arch: "64"
          - os: ubuntu-latest
            python-version: "3.10"
            arch: "aarch64"
    uses: ./.github/workflows/worker.yaml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      python-version: ${{ matrix.python-version }}
      ref: ${{ github.ref_name }}
